# Image of workspace. Learn more: https://www.gitpod.io/docs/configure/workspaces/workspace-image
image: gitpod/workspace-full:latest

vscode:
  extensions:
    - miragon-gmbh.miranum-ide
    - vsls-contrib.gitdoc
